version: 1.0.{build}
configuration: Release
test: off
pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
- path: ProbabilisticDataStructures\bin\Release
  name: ProbabilisticDataStructures-v$(appveyor_build_version)
