version: 1.0.{build}
test: off
pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal
artifacts:
- path: ProbabilisticDataStructures\bin\Release
  name: ProbabilisticDataStructures-v$(appveyor_build_version)